### ISSUE TITLE
BuildingTeamHub - download location incorrect

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#10]
For the following:

"Click on the Test and Distribute selector from the left panel under Distribute and then the Export button to download and save the LunchMenu.zip manifest file to your desktop."

The download location was the "Downloads" folder.

**Comment by tklarslynch** [comment]
Fixed. Ready to close.

**Comment by cbarkerms** [comment]
thanks, closing!
