### ISSUE TITLE
Modernize: Windows Hello Application Identity Missing from Lab

### ISSUE THREAD

**Issue by seansparkman** [Microsoft/InsiderDevTour18-Labs#100]
I do not see the application identity from the Moscow Video of Insider Dev Tour inside of the labs.  I tried running the Package Deployment Project as the startup project, and the Login button still shows username and password, not the Hello screens.

**Comment by seansparkman** [comment]
There seems to a missing file: MicrosoftPassportHelper.cs

**Comment by seansparkman** [comment]
Here is the documentation from the lab that I am looking at.  https://docs.microsoft.com/en-us/labs/insiderdevtour2018/modernize/index?ocid=idt_labs_cta_web2lab_modernize

**Comment by cbarkerms** [comment]
The Moscow video is showing the session demos - these are different to the labs. For the modernize lab there is not a Windows Hello step - we use toast notifications instead to demonstrate Windows APIs as this does not have a hardware requirement for TPM etc. If you are presenting the content for modernize there is a separate repo and steps that your event lead can share with you. Please let me know if this doesn't help clarify.

**Comment by cbarkerms** [comment]
Closing for now, but please let me know if you have outstanding questions.
