### ISSUE TITLE
Microsoft Graph docs - missing pre-requisites

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#14]

**Comment by cbarkerms** [comment]
Please move pre-requisites closer to the top of the page - they are very hard to find where they are.

**Comment by cbarkerms** [comment]
see this as an example for pre-reqs: https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/pwa/index?branch=insiderdevtour%2Fdev&ocid=idt_labs_cta_web2lab_pwa

**Comment by michael-hawker** [comment]
The Objectives of the lab should also be at the top on the Introduction page.
