### ISSUE TITLE
Graph docs - create separate .md file for "Getting Started with Quick Start"

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#21]
"Getting Started with Quick Start" onwards should be on it's own page.  Please also update the .yml to reflect the update in structure.

**Comment by cbarkerms** [comment]
Update .yml/.md files to help with better tutorial flow.  Examples:

1. create separate .md file for "Getting Started with Quick Start"
2. create separate .md file for "Integrating with office"
3. create separate .md file for "Writing to the Timeline" (this can include the PWILO/Cortana part)

**Comment by michael-hawker** [comment]
Yeah, I was just going to say the 'Introduction' is super long.
