### ISSUE TITLE
ML - please breakout pages further - separate markdown, update yml

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#23]
Example:

Emotion detection with Face API (Lab-part-2.md) should become something like:

Emotion detection with Face API (Cloud) (Lab-part-2.md) 
Emotion detection with Windows ML (edge) (Lab-part-2b.md)

And the .yml file will need to be updated accordingly.

**Comment by fpelaez** [comment]
Updated on commit 
https://github.com/MicrosoftDocs/labs-pr/commit/9452bf96dd4fa2911ecf1a018ed92de36ce2494b

**Comment by cbarkerms** [comment]
YML not updated so not seeing the changes. I will fix and push an update.

**Comment by cbarkerms** [comment]
https://github.com/MicrosoftDocs/labs-pr/commit/e29d23dfd43dedfcb0767223e3ef468df33424d6
