### ISSUE TITLE
Graph - English grammar / phrase check required

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#25]
Examples:

MS Graph => either "Graph" or "Microsoft Graph"
"In UWP project go to Helpers/OneDriverHelper.cs" => "In the UWP project go to …"
"Integrating with office" => "Integrating with Office"
"Advance app feature" => "Cortana integration"

**Comment by t-mahigh** [comment]
Quite a few examples of this in the first part as well with titles like "Brief explanation of what is Graph" as well as some missing commas in longer sentences.

**Comment by skommireddi** [comment]
Microsoft Graph has a new future: UserActivity. Is it future or feature?

**Comment by michael-hawker** [comment]
> Microsoft Graph is an API built in Office 365 that allows developers to integrate with devices, Office 365, Azure and develop more intelligent and productive applications.

… Office 365, and Azure and to develop more...

It's a busy sentence though.

**Comment by michael-hawker** [comment]
> At the core of Microsoft Graph are the concepts of the user and group.

Suggest: There are two primary entities used in the Microsoft Graph, a user and groups.

Then I'd indent/bullet the next two paragraphs to make the user and group explanations stand out (maybe even start with a bolded `User` and `Group`).

**Comment by skommireddi** [comment]
Download project form here. Spelling is wrong - from, not form
