### ISSUE TITLE
Modernize - change order of sections

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#26]
Distribution and versioning should come first as some Windows 10 APIs require a package identity.

1. Distribution and versioning
2. UI modernization
3. Windows 10 APIs - Toast
3. Adaptive cards

**Comment by MarcosCobena** [comment]
Done; however I've just noticed you put @cbarkerms W10 APIs before Adaptive Cards, which I left just after. Thinking about it now see it better as it's, but won't close this until you double-check it:

https://github.com/MicrosoftDocs/labs-pr/commit/0f1f6c6f1bf4333a1ec5e81e1cbd1cd9efd0e183

**Comment by cbarkerms** [comment]
i like the order you have - closing, thanks!
