### ISSUE TITLE
Modernize - add example of calling Windows 10 APIs

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#27]
We need to show an example of calling into Windows 10 APIs from a Desktop app - example: Toast notifications

**Comment by MarcosCobena** [comment]
Hi Chris,

This' done now —every commit I've made today:

https://github.com/MicrosoftDocs/labs-pr/tree/insiderdevtour/dev/labs/insiderdevtour2018/modernize
