### ISSUE TITLE
Office 365 - adjust structure

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#28]
Adjust .md/.yml files to give the following:

"Exercise 1: Create a Team" (it's own .md file - and remove the "Exercise 1" numbering)
"Graph APIs" (it's own .md file - and remove the "Exercise 2" numbering)
"Canvases across Office 365" (it's own .md file)

**Comment by cbarkerms** [comment]
@tklarslynch

**Comment by tklarslynch** [comment]
Fixed. Ready to close.
