### ISSUE TITLE
MixedReality: Terminology

### ISSUE THREAD

**Issue by GrantMeStrength** [Microsoft/InsiderDevTour18-Labs#29]
The term "HMDU MR experience" is used in the Introduction. HMDU is not a recognized term. Even if it was meant to be HMD (for Head Mounted Display), that is not recommended. "Mixed Reality Headset" is the preferred term.

BTW, do not google HMDU. This is a Pri 0 Policheck issue.

**Comment by t-mahigh** [comment]
All references have been removed and replaced with "immersive headset"

**Comment by cbarkerms** [comment]
thanks!
