### ISSUE TITLE
Mixed Reality - MRTK default project settings different

### ISSUE THREAD

**Issue by stammen** [Microsoft/InsiderDevTour18-Labs#30]
The docs show this for the default settings:

![image](https://user-images.githubusercontent.com/1226490/40560657-84cae1d4-600f-11e8-9417-179894756fad.png)

My fresh install of Unity 2017.4.2 and fresh import of the Holotoolkit.unitypackage displayed this:

![image](https://user-images.githubusercontent.com/1226490/40560717-b6fe49ac-600f-11e8-9834-1268ad5d5d80.png)

Note: Use Toolkit-specific InputManager axes was NOT enabled by default in my fresh install.

It would be better to state the exact settings you require to be selected.

Also user should click Apply

**Comment by t-mahigh** [comment]
Updated wording to include "hit Apply" and to prompt user to make sure that Toolkit-specific InputManager axes is checked.

**Comment by cbarkerms** [comment]
thanks!
