### ISSUE TITLE
MixedReality: Terminology & Missing Lab Files

### ISSUE THREAD

**Issue by GrantMeStrength** [Microsoft/InsiderDevTour18-Labs#31]
In the "Exporting a WinMR UWP app from Unity" section:

* "WinMR" and "Win MR" are not the correct terms. Use Windows Mixed Reality.

* The first step requires importing files from the "lab files". There is no link to these files, and so I am 
blocked from getting any further.

* Use of the phrase "super simple" is discouraged. It may be "super simple" to the author, but not the person trying to do it.

**Comment by t-mahigh** [comment]
Links to project packages have been pushed, and terminology has been updated to read "Windows Mixed Reality" and "The Mixed Reality Toolkit will be helpful for this task."

**Comment by cbarkerms** [comment]
thanks all!
