### ISSUE TITLE
Mixed Reality - Images are different than installed version of MRTK

### ISSUE THREAD

**Issue by stammen** [Microsoft/InsiderDevTour18-Labs#32]
I am getting different options from the images in the docs. The docs show this for the "Apply Mixed Reality Scene Settings"  

![image](https://user-images.githubusercontent.com/1226490/40561043-9d4abaf8-6010-11e8-9edb-73fe8e00ab59.png)

The Holotoolkit.unitypackage from the InsiderDevTour18-Labs shows this:

![image](https://user-images.githubusercontent.com/1226490/40561118-df005732-6010-11e8-8cde-bceeb7568f28.png)

Did you use the same version of the  Holotoolkit.unitypackage when you created the docs?

**Comment by t-mahigh** [comment]
Updated the screenshot to match the current version of Holotoolkit

**Comment by stammen** [comment]
Thanks!
