### ISSUE TITLE
Mixed Reality - No Scenes are present error when "Open in Visual Studio"

### ISSUE THREAD

**Issue by stammen** [Microsoft/InsiderDevTour18-Labs#33]
When following these instructions:

To deploy the project to an immersive headset.
Navigate to the Build Window: Mixed Reality Toolkit -> Build Window.
Click on Open in Visual Studio.
Navigate to Build -> Configuration Manager in Visual Studios or use the drop-down at the top of the page and select x64 in your platform options.
In the debug toolbar, select "Local Machine" as the target (or remote device if you are pushing to another machine).
Run the app by hitting play.

I get the following error:

![image](https://user-images.githubusercontent.com/1226490/40561267-73205e3a-6011-11e8-8298-95074bee8c70.png)

Need instructions on how to make sure the scene is added to the build.

**Comment by t-mahigh** [comment]
Did you see the step above that says: 

> Next, navigate to your Build Settings using `ctrl + shift + B`, select Universal Windows Platform, and then click Switch Platform. Add your open scene to the build by checking the box next to your scene's name and clicking "Add Open Scenes".

It may have been pushed after you went through the lab.

**Comment by stammen** [comment]
Thanks for the update.
