### ISSUE TITLE
PWA: Grammar

### ISSUE THREAD

**Issue by GrantMeStrength** [Microsoft/InsiderDevTour18-Labs#34]
"In these labs you will be introduced how to build a Progressive web application". 

would be better as:

"This lab will explain how to build a Progressive Web App (PWA)".

**Comment by cbarkerms** [comment]
NOTE: @GrantMeStrength has performed grammar fixes up to lab-part-3.md.  @fpelaez , @spertusatti can you please complete the rest thanks
