### ISSUE TITLE
PWA: Grammar

### ISSUE THREAD

**Issue by GrantMeStrength** [Microsoft/InsiderDevTour18-Labs#36]
* Note *
I am working through the content, and will submit a PR with some grammar improvements.

This lab _really_ needs a good copy edit. Here are some suggestions for the PWA Foundations page.

"Technologically speaking" - remove this text.

"Standard Manifest: The site should be controlled by a W3C manifest that determines the experience and behavior of your PWA"

would be better as

"Standard manifest file: The site requires a manifest file to define the features and behavior of the PWA. The file follows the W3C standard".

"Since at their core PWAs are still websites, they’re already supported on numerous platforms like Windows, Android, iOS, and Mac. They can be enhanced over time to function more like native apps, and even use native APIs, on supported platforms. This can turn your website into a Rockstar app by combining the best of the web and native application worlds. Plus, the work of turning your website into a PWA can also improve your website’s experience."

would be better as:

"PWA apps are still websites, and are therefore supported on most platforms including Windows, Android, iOS and Mac. They can enhanced to function more like native apps, and even use native APIs on support platforms. A PWA can combine the best features of a web site and a native application."

i.e. removing "Rockstar app"

"PWAs aren't very different that a web application, when you access to a PWA you will see the same as a simple web application. After complete this lab, your PWA will looks like this:"

ok, I give up :-) This sentence alone has about 10 issues :-)

**Comment by cbarkerms** [comment]
NOTE: @GrantMeStrength has performed grammar fixes up to lab-part-3.md.  @fpelaez , @spertusatti can you please complete the rest thanks
