### ISSUE TITLE
Get 403 Forbidden when navigating backwards from lab

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#38]
![image](https://user-images.githubusercontent.com/24302614/40563013-1b450902-6018-11e8-9dd9-0250cb5ebc68.png)

## Repro:
1. Start InPrivate session
2. From [labs page](http://insiderdevtour-test.azurewebsites.net/labs)
3. Click Graph's `Start Lab` 
4. Login
5. Let doc page load
6. Hit back button in browser.

## Expected
Return to lab selection page

## Actual
Get 403 forbidden page as in image above.

Not sure if this matters since there's permissions on it currently, but figured I'd report it, just in case.

**Comment by cbarkerms** [comment]
thanks for raising - closing by-design - wont have issue when we roll out
