### ISSUE TITLE
Graph - Typos in index file

### ISSUE THREAD

**Issue by t-mahigh** [Microsoft/InsiderDevTour18-Labs#42]
"title: Drive user engagement across all your devices with Microsoft Graph"
- Should each word be capitalized?

"In this lab **your** learn what is graph, how use it and the possibilities that offers us. You write C# code and see **tthe** results in UWP App."
- Phrasing is a bit off here as well.

"title: Integrating MS Graph into **you** app"

**Comment by cbarkerms** [comment]
"Should each word be capitalized?" No.

Yes those typos/grammar need fixing - closing as duplicate of this: https://github.com/Microsoft/InsiderDevTour18-Labs/issues/25
