### ISSUE TITLE
PWA: Publish your PWA and PWA on Windows

### ISSUE THREAD

**Issue by GrantMeStrength** [Microsoft/InsiderDevTour18-Labs#43]
Publish your PWA

The instructions say "Pull the "manifest.json" file and the "images" folder that are inside of the PWA folder "
It is unclear what "pull" means in this context. Delete? Copy?

PWA on Windows
Broken images.

Some later pages in the git repo don't appear to be published at all, at least they aren't in the TOC. Maybe by design, as they look a little rough.

**Comment by davrous** [comment]
Step 6: https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/pwa/index?branch=insiderdevtour%2Fdev&ocid=idt_labs_cta_web2lab_pwa&tutorial-step=6
And Step 7: https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/pwa/index?branch=insiderdevtour%2Fdev&ocid=idt_labs_cta_web2lab_pwa&tutorial-step=7 

have both broken images indeed

**Comment by cbarkerms** [comment]
fixed, thanks!
