### ISSUE TITLE
Graph Why is this useful should have links to samples

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#44]
There's a lot of great stuff called out in the [Why is this useful](https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/graph/index?branch=insiderdevtour%2Fdev&ocid=idt_labs_cta_web2lab_graph) section of the Graph introduction, but it'd be great to actually link to samples/docs showing how to do these various things.  Otherwise it's just taunting or frustrating if those are things I know I want to do.

**Comment by michael-hawker** [comment]
@rbermejotokiota couple of spacing issues around the colons.  Would it make sense to just have it be as a parenthetical at the end like `(link)` rather than a blob of text after a colon?  The repeated 'Microsoft Graph` text makes that a lot busier now.

**Comment by cbarkerms** [comment]
fixed https://github.com/MicrosoftDocs/labs-pr/commit/6e812fef1922817fa2bc6045913314ae6d77600a
