### ISSUE TITLE
ML - can't find nuget package Microsoft.Toolkit.Uwp.UI.Controls (v3.0.0)

### ISSUE THREAD

**Issue by serenaz** [Microsoft/InsiderDevTour18-Labs#47]
For the "Emotion Detection with Face API" section, I can't find Microsoft.Toolkit.Uwp.UI.Controls (v3.0.0) in VS, so CameraPreview doesn't exist in my project.

**Comment by nmetulev** [comment]
3.0.0 will be released on Wednesday. You can use this nuget source for testing: https://dotnet.myget.org/gallery/uwpcommunitytoolkit

**Comment by cbarkerms** [comment]
closing for now
