### ISSUE TITLE
Flow from Creating Team page to Graph not smooth

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#5]
At the end of the “Exercise 1: Create a Team” page, you have a section on “Graph APIs” – It doesn’t seem to flow naturally from the previous point (number 11).  Can you please be a bit more descriptive about what you will do next – example: “read on to see what a developer can do with the Microsoft Graph”.

**Comment by tklarslynch** [comment]
Fixed. Ready to close.

**Comment by cbarkerms** [comment]
thanks!
