### ISSUE TITLE
Modernize - improve grammar and markdown (including numbering steps)

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#50]
@fpelaez - I already did this for lab-part-0 -> lab-part-2.  Just lab-part-3 is left so please complete that and use 0-2 as a reference. thanks!

**Comment by MarcosCobena** [comment]
Done, although won't close it until anyone else could check grammar:

https://github.com/MicrosoftDocs/labs-pr/commit/f4c492d28b478361cef4c470f0cd6b70832c5534

lab-part-4 has also been made with all this in mind :-)

**Comment by cbarkerms** [comment]
fixed
