### ISSUE TITLE
Graph - Link in Getting Started doesn't point to Console Project

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#54]
https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/graph/index?branch=insiderdevtour%2Fdev&ocid=idt_labs_cta_web2lab_graph&tutorial-step=2

Under 'Sample API calls' and `Create a console app` it doesn't link to the project directory like the previous sample did.  It should link here I'm assuming: https://github.com/Microsoft/InsiderDevTour18-Labs/tree/master/graph/Microsoft.Graph.HOL.ConsoleBase

It could be useful to put the git clone link in the documentation as well?

(Also, should this section be broken up a bit.  We do the app setup, then we do this separate investigation in the graph explorer, and then we go to the console app...?)

**Comment by cbarkerms** [comment]
fixed
