### ISSUE TITLE
Graph - Add reminder in Console App sample about if they get an error about reply address

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#55]
First, got red squiggles when opening project (they went away after I built, but may want to call it out).

More importantly, I followed the steps and got this:

![image](https://user-images.githubusercontent.com/24302614/40673764-94eec632-6327-11e8-88a4-53fa650f025c.png)

App just hung after I closed the window and didn't do anything, what do I do?

I have my app id and return url in `<appSettings>` in the `app.config` under the root `<configuration>` element.

**Comment by michael-hawker** [comment]
Nevermind, I forgot to hit save on the registration page :(.  Could be a handy reminder at that point in the doc though that if they see that message `No reply address is registered for the application.` that it means they most likely forgot to hit save in the initial step at the top of the page.

**Comment by cbarkerms** [comment]
Fix pushed to https://github.com/MicrosoftDocs/labs-pr/commit/9f8b4fe8b9219ab97e513b11cc42fbebbbbe0317

Awaiting merge into master/live
