### ISSUE TITLE
Graph - Managing Files With Microsoft Graph formatting mangled?

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#59]
Tried in Edge and Firefox:
https://review.docs.microsoft.com/en-us/labs/insiderdevtour2018/graph/index?tutorial-step=3&branch=insiderdevtour%2Fdev

All the markdown is showing for this section instead of being formatted:

![image](https://user-images.githubusercontent.com/24302614/40676112-99b2bbcc-632e-11e8-9af4-ece4f262821b.png)

**Comment by cbarkerms** [comment]
fixed - thanks!
