### ISSUE TITLE
VM Lab Panel Navigation is Wonky

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#60]
The panel next to the VM is nice, but there's no way to jump to a particular lab.  (It also has the same docs issue/bug about clicking next not jumping to the top.)

After clicking next through all the pages, it has the option to go to the next lab, though it says 'Graph Lab':

![image](https://user-images.githubusercontent.com/24302614/40853469-0172b5f4-6583-11e8-9a6e-0017d9a50336.png)

Except, this was the graph lab...

Also, after clicking it, you get this:
![image](https://user-images.githubusercontent.com/24302614/40853382-bbf1040e-6582-11e8-8488-dd8ea5e4a02b.png)

Which is the link to the MR lab.

**Comment by cbarkerms** [comment]
closing - there are a few issues here that are logged elsewhere. e.g. https://github.com/Microsoft/InsiderDevTour18-Labs/issues/71, https://github.com/Microsoft/InsiderDevTour18-Labs/issues/67

**Comment by michael-hawker** [comment]
@cbarkerms we could differentiate this one to ensure that the navigation between labs is possible when clicking the final next?
