### ISSUE TITLE
VM - Git missing

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#61]
Would be nice to have git on the machines (as otherwise grabbing samples is hard):

![image](https://user-images.githubusercontent.com/24302614/40854686-0d34e35e-6587-11e8-862b-ab355eb60207.png)

This also throws a warning up in VS Code (which just installing git doesn't always fix, so it'd be good to check):

![image](https://user-images.githubusercontent.com/24302614/40854597-cea4b290-6586-11e8-8243-d06017d1d922.png)

![image](https://user-images.githubusercontent.com/24302614/40854621-dfba6304-6586-11e8-9632-0bebcb04052d.png)

**Comment by cbarkerms** [comment]
now implemented
