### ISSUE TITLE
VM - Pre-install lab samples

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#62]
It'd be nice if the VMs had all the lab code pre-installed so the user didn't have to spend time fetching them for each lab (which is difficult now as git isn't installed so they can't clone the repo out of the box - see #61).

**Comment by cbarkerms** [comment]
we will look at having a C:\Lab folder where we have run the following command ahead of time:

git clone https://github.com/Microsoft/InsiderDevTour18-Labs.git

**Comment by cbarkerms** [comment]
now implemented
