### ISSUE TITLE
VM - Can't expand screen size :(

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#63]
Even if I go full screen or try the 'Fit window to machine' option, the display size is fixed and won't take up my entire browser space available:

![image](https://user-images.githubusercontent.com/24302614/40854943-df47e364-6587-11e8-8e54-613eaaa865d2.png)

The resolution is tight on this machine, so being able to fill the browser window would be nice.

**Comment by cbarkerms** [comment]
vendor agreed to improve this experience for when we go live
