### ISSUE TITLE
VM - No access to clipboard

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#64]
If I'm in another tab on my machine and copy something out of the doc window, I can't paste it into the VM (easily).

It may be nice with the panel on the right to have it start with a quick overview of the VM and call out the commands menu:

![image](https://user-images.githubusercontent.com/24302614/40855365-41c6e002-6589-11e8-89b1-7a7f5cea6370.png)

Though that still requires pasting again, so there's a multi-step process for pasting, but it took a bit to realize I could do this at first.

**Comment by cbarkerms** [comment]
vendor agreed to improve experience for when this goes live
