### ISSUE TITLE
VM - Lab closes without warning - (after a period of time?)

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#65]
Went to lunch and came back after being away for about an hour?

![image](https://user-images.githubusercontent.com/24302614/40858421-0e3036a8-6593-11e8-9762-ba9b64e60691.png)

If I refresh the page I get:

![image](https://user-images.githubusercontent.com/24302614/40858447-2718c3ba-6593-11e8-8eea-1406066d1347.png)

Soumya was actively working on hers though and got booted.

**Comment by skommireddi** [comment]
Yup, I was in the middle of the lab and got kicked out.

**Comment by cbarkerms** [comment]
vendor increased timeout from 1 hour to 2 hours
