### ISSUE TITLE
Machine Learning Lab - Multiple Issues on Emotion detection with Face API (cloud) section

### ISSUE THREAD

**Issue by skommireddi** [Microsoft/InsiderDevTour18-Labs#66]
1. Add this to using statements: using Microsoft.Toolkit.Uwp.Helpers;

2. In 4. Detect emotion using Azure Cognitive Services section, steps 2 and 3 are repetitive and already added in step 2 above. Also there is not DetectEmotion(bitmap) defined.

3. In  timer.Elapsed += Timer_Elapsed; timer.Start(); There is no timer variable defined, change it to stopwatch as defined in previous step.

**Comment by cbarkerms** [comment]
Fix pushed to dev branch https://github.com/MicrosoftDocs/labs-pr/commit/c6eff485f7fdd269c28829ad8beec43779101f2e

Awaiting merge into master/live.
