### ISSUE TITLE
Machine Learning Lab - Can't test as no camera source available on vm

### ISSUE THREAD

**Issue by skommireddi** [Microsoft/InsiderDevTour18-Labs#68]
I finished the first part of the machine learning lab - Emotion detection with Face API (cloud) and when I run the app, it is blank since no camera source is available on vm. So there is no way to test it .

The entire lab is dependant on camera and frames being available.

**Comment by skommireddi** [comment]
![image](https://user-images.githubusercontent.com/30093161/40865293-6ecae940-65ac-11e8-8fab-bea5d1a6bad7.png)

**Comment by cbarkerms** [comment]
learnt from vendor this is unfortunately not possible today - we will not enable VM hosting for ML at this stage - we may revise later
