### ISSUE TITLE
No instructions on getting Azure setup on Building team hubs section

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#7]
Create Azure App Service
	“Login to Azure portal” – how / where?
	Please describe how to get a free trial subscription.

**Comment by tklarslynch** [comment]
Fixed. Ready to close.

**Comment by cbarkerms** [comment]
@tklarslynch please provide the portal url - i.e. portal.azure.com

**Comment by tklarslynch** [comment]
Fixed. Ready to close.
