### ISSUE TITLE
Modernize - "Enable Automatic Updates" checkbox is disabled

### ISSUE THREAD

**Issue by shweaver-MSFT** [Microsoft/InsiderDevTour18-Labs#75]
In the Distribution and versioning section, when creating packages for sideload, the "Enable Automatic Updates" checkbox was disabled. I can't uncheck it as the guide indicates. This is because the target/min versions are not set to latest, which is accomplished in another step later on. 

"Firstly, choose I want to create packages for sideloading, Next uncheck Enable automatic updates for now."

https://docs.microsoft.com/en-us/labs/insiderdevtour2018/modernize/index?ocid=idt_labs_cta_web2lab_modernize&tutorial-step=1

**Comment by cbarkerms** [comment]
fixed: https://github.com/MicrosoftDocs/labs-pr/commit/62018a0d1858c060c6800d4f545cc4e383416263

awaiting merge into master/live
