### ISSUE TITLE
Modernize - Adaptive card visual is clipped

### ISSUE THREAD

**Issue by shweaver-MSFT** [Microsoft/InsiderDevTour18-Labs#79]
In the Modernize lab, Adaptive Card section:

Step 1 of *Creating your card* doesn't render the card correctly. The XAML needs an additional property added to render correctly:

    Grid.Row="1"

**Comment by cbarkerms** [comment]
nice catch. fixed: https://github.com/MicrosoftDocs/labs-pr/commit/62018a0d1858c060c6800d4f545cc4e383416263

awaiting merge into master/live
