### ISSUE TITLE
Exercise 3 in Building Team hubs section has invalid assets link

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/InsiderDevTour18-Labs#8]
Unable to get sample project from following link:

Download this assets.zip file and unpack the images and JSON to the lunchmenu\src\assets folder.

**Comment by cbarkerms** [comment]
Please push the assets.zip to here: https://github.com/Microsoft/InsiderDevTour18-Labs/tree/master/office365

**Comment by tklarslynch** [comment]
Fixed. Ready to close.

**Comment by cbarkerms** [comment]
thanks - closing!
