### ISSUE TITLE
Modernize - Package install failure

### ISSUE THREAD

**Issue by shweaver-MSFT** [Microsoft/InsiderDevTour18-Labs#83]
In the Modernize lab, Enabling automatic updates section:

The last step shows the index.html generated during the packaging process, but the app can't actually be installed. Instead, the app installer shows an error:

> Error in parsing the app package.

**Comment by cbarkerms** [comment]
fixed: https://github.com/MicrosoftDocs/labs-pr/commit/62018a0d1858c060c6800d4f545cc4e383416263

awaiting merge into master/live

**Comment by cbarkerms** [comment]
fixed: https://github.com/MicrosoftDocs/labs-pr/commit/62018a0d1858c060c6800d4f545cc4e383416263

awaiting merge into master/live
