### ISSUE TITLE
Graph Navigation View project should be expanded all the time

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/InsiderDevTour18-Labs#85]
It'd be nice if the NavigationView was expanded all the time as all the icons are the same:

![image](https://user-images.githubusercontent.com/24302614/41128451-0aab7680-6a63-11e8-9c36-02fec843c4e1.png)

**Comment by cbarkerms** [comment]
this is expanded all of the time during my test - even though i wasnt aware the code had changed.  closing.
