### ISSUE TITLE
PWA - Error running Knowzy app inside VM.

### ISSUE THREAD

**Issue by skommireddi** [Microsoft/InsiderDevTour18-Labs#87]
In Build a Responsive web app section, after I get the PWA source code and run the app, I get this error

![image](https://user-images.githubusercontent.com/30093161/41186089-1031a89e-6b45-11e8-9a0c-656def214d91.png)

**Comment by cbarkerms** [comment]
cause identified. need .net core 1.1 installed. will get this included in the vm image.

**Comment by cbarkerms** [comment]
fixed.
